# This workflow build and push Docker image to docker hub
# https://docs.docker.com/build/ci/github-actions/cache/
name: dockerhub

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      airflow_version:
        description: 'Airflow version to build'
        required: false
        default: '3.0.4'
        type: string

env:
  DEFAULT_AIRFLOW_VERSION: '3.0.4'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Determine Airflow version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.airflow_version }}" ]]; then
            AIRFLOW_VERSION="${{ github.event.inputs.airflow_version }}"
          else
            AIRFLOW_VERSION="${{ env.DEFAULT_AIRFLOW_VERSION }}"
          fi
          echo "airflow_version=${AIRFLOW_VERSION}" >> $GITHUB_OUTPUT

      - name: Generate tags
        id: tags
        run: |
          AIRFLOW_VERSION=${{ steps.version.outputs.airflow_version }}
          TAGS="${{ secrets.DOCKER_HUB_USERNAME }}/airflow-conda:airflow-${AIRFLOW_VERSION}"
          
          # Add latest tag for master branch
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            TAGS="${TAGS},${{ secrets.DOCKER_HUB_USERNAME }}/airflow-conda:latest"
          fi
          
          # Add version tag if this is a git tag
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            TAGS="${TAGS},${{ secrets.DOCKER_HUB_USERNAME }}/airflow-conda:${TAG_NAME}"
          fi
          
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build and push to docker hub
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tags.outputs.tags }}
          build-args: |
            AIRFLOW_VERSION=${{ steps.version.outputs.airflow_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: |-
            linux/amd64
            linux/arm64

      - name: Image digest
        if: github.event_name != 'pull_request'
        run: echo ${{ steps.build.outputs.digest }}

      - name: Create Release
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: airflow-${{ steps.version.outputs.airflow_version }}
          release_name: Release airflow-${{ steps.version.outputs.airflow_version }}
          body: |
            Release for Airflow version ${{ steps.version.outputs.airflow_version }}
            Docker Image: https://hub.docker.com/r/andgineer/airflow-conda/tags?page=&page_size=&ordering=&name=airflow-${{ steps.version.outputs.airflow_version }}
          draft: false
          prerelease: false
